name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: docker

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}
      
      - name: Docker meta
        id: metaraw
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/media-byte/wantarr
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
        
      - name: Build and publish
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.metaraw.outputs.tags }}
          labels: ${{ steps.metaraw.outputs.labels }}
